/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ResumeResumeIDImport } from './routes/Resume/$resumeID'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResumeResumeIDRoute = ResumeResumeIDImport.update({
  id: '/Resume/$resumeID',
  path: '/Resume/$resumeID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Resume/$resumeID': {
      id: '/Resume/$resumeID'
      path: '/Resume/$resumeID'
      fullPath: '/Resume/$resumeID'
      preLoaderRoute: typeof ResumeResumeIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Resume/$resumeID': typeof ResumeResumeIDRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Resume/$resumeID': typeof ResumeResumeIDRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Resume/$resumeID': typeof ResumeResumeIDRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Resume/$resumeID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Resume/$resumeID'
  id: '__root__' | '/' | '/Resume/$resumeID'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeResumeIDRoute: typeof ResumeResumeIDRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeResumeIDRoute: ResumeResumeIDRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Resume/$resumeID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Resume/$resumeID": {
      "filePath": "Resume/$resumeID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
